### ISSUE TITLE
Use Items On Players

### ISSUE THREAD

**Issue by joeboby** [Rocket-Eagle/Rocket-Eagle#10]
As a self isolator, I want to be able to play a game with others and be able to use items that can help me win

**Acceptance Test**
- From the main menu select multiplayer
- Create a display name 
- Choose to host or join a lobby
- Once in a lobby, start the game 
- Pick up an item crate 
- Verify a random item is shown in the UI 
- Use the item 
- Verify the item works properly
- Verify the item properly affects player
- Verify the item can no longer be used 
- Verify the item is no longer displayed in the player UI

**Risk**
- Medium

**Story Points**
- Story Points: 6

**Comment by mccarko** [comment]
Single player item time
worktime: 4 hours

**Comment by penner75** [comment]
Multiplayer Items: 1.5 hours
