### ISSUE TITLE
Add method to change sprite to the BirdController

### ISSUE THREAD

**Issue by BrittBarber** [Rocket-Eagle/Rocket-Eagle#118]
Relates to issue #11

**Comment by joeboby** [comment]
Was not able to use this method as the BirdController class is not active from the main menu (they are in different scenes). Thus I had to create a different way to set the skin. The selected skin is now saved to a file and loaded in during the start() in BirdController. This also means that selected skins persist between sessions which is great!

**Comment by joeboby** [comment]
4 hours

**Comment by BrittBarber** [comment]
Britt 2 hours
