### ISSUE TITLE
Get Into the Game

### ISSUE THREAD

**Issue by joeboby** [Rocket-Eagle/Rocket-Eagle#2]
As a gamer, I want to be able to get into the game

**Acceptance Test:**
- Launching the game works
- Loading the game keeps the data from previous rounds (skins purchased stay purchased)

**Risk**
- Medium

**Story Points**
- Story Points: 4

**Comment by BrittBarber** [comment]
0.5 hours for task #62

**Comment by BrittBarber** [comment]
0.5 hour for task #49

**Comment by joeboby** [comment]
2 hours

**Comment by mccarko** [comment]
2.5 hours
