### ISSUE TITLE
See Finishing Time

### ISSUE THREAD

**Issue by joeboby** [Rocket-Eagle/Rocket-Eagle#4]
As a gamer, I want to be able to see how fast I played the game to compare it to others

**Acceptance Test**
- Time is displayed to the user after a match
- Time is accurate (starts at zero, isn't dependent on the movement speed of the bird)

**Risk**
- Low

**Story Points**
- Story Points: 4

**Comment by mccarko** [comment]
1.5 hours task #47  #45

**Comment by penner75** [comment]
2 hours task #33, #37, #38

**Comment by penner75** [comment]
#133 Fix Countdown Issue: .5 hours
