### ISSUE TITLE
Move the player

### ISSUE THREAD

**Issue by joeboby** [Rocket-Eagle/Rocket-Eagle#5]
As a player, I want to be able to move as the player

**Acceptance Test**
- Moving is consistent
- Avoid clipping into object
- Collisions with the items correctly gives a player an object
- Collisions with a pipe (or equivalent) resets the players speed and moves them back
- Can't move off the screen (top bottom or past the finish line)

**Risk**
- Medium

**Story Points**
- Story Points: 8

**Comment by BrittBarber** [comment]
1 hour for task #51

**Comment by penner75** [comment]
5 hours for tasks #48, #50, #52 (first issues done, created scenes for testing)

**Comment by penner75** [comment]
.5 hours fixing Pipe clipping #148
