### ISSUE TITLE
Play Unique Levels

### ISSUE THREAD

**Issue by joeboby** [Rocket-Eagle/Rocket-Eagle#7]
As a store clerk, I want to be able to play unique games over and over again as I do nothing in my job

Acceptance Test
- From the main menu select single player
- Choose a map
-  Verify the player spawns into the level 
- Verify the user can pass the level 
- Verify the user can complete laps and the correct lap is being displayed
- Verify the finish line exists and crossing it finishes the race
- Go back to the main menu 
- Repeat this process for every map in the map selector screen

**Risk**
- High

**Story Points**
- Story Points: 8

**Comment by mccarko** [comment]
3h so far for task #31  (still need more maps in future)

**Comment by mccarko** [comment]
final time for all levels
worktime: 7 hours

**Comment by penner75** [comment]
#171 Add to multiplayer: 1 hour
