### ISSUE TITLE
Join Lobby

### ISSUE THREAD

**Issue by joeboby** [Rocket-Eagle/Rocket-Eagle#8]
As a self isolator, I want to be able to join a game with friends

**Acceptance Test**
From Hosting
- From main menu select multiplayer 
- enter a display name 
- select host a lobby
- have friends join your lobby  
   
From Join
- From main menu select multiplayer 
- enter a display name 
- select a lobby 
- enter the lobby code 
- join your friend's lobby 

**Risk**
- High

**Story Points**
- Story Points: 8

**Comment by BrittBarber** [comment]
10 hours for task #106
