### ISSUE TITLE
Play With Other Players

### ISSUE THREAD

**Issue by joeboby** [Rocket-Eagle/Rocket-Eagle#9]
As a self isolator, I want to be able to play a game with a friend so that I don’t go crazy

**Acceptance Test**
- From the main menu select multiplayer
- Create a display name 
- Join or host a lobby 
- Ready up 
- Start the game 
- Verify all lobby players joined the game 
- Verify all players are properly identified
- Verify each player can only control one character
- Verify each player can control the correct character

**Risk**
- High

**Story Points**
- Story Points: 8

**Comment by BrittBarber** [comment]
3 hours for task #107

**Comment by penner75** [comment]
12 hours for task #107

**Comment by penner75** [comment]
Multiplayer Skins: 3 hours #157

**Comment by penner75** [comment]
Enter Multiplayer After Single Player #169:1.5 hours
